(function(g){var window=this;var ywa=function(a,b){var c=[];g.Ll(b,function(a){try{var b=g.yD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.xD(b)&&c.push(a):c.push(a)},a);
return c},zwa=function(a,b){var c=ywa(a,b);
(0,g.H)(c,function(a){g.yD.prototype.remove.call(this,a)},a)},x8=function(a,b){g.k1.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.T=a;this.F={};this.R(a,"onMdxReceiversChange",this.I);this.R(a,"presentingplayerstatechange",this.I);this.I()},Awa=function(){var a=g.XG;
zwa(a,a.g.Xd(!0))},y8=function(a){g.zH.call(this,"ScreenServiceProxy");
this.dd=a;this.o=[];this.o.push(this.dd.$_s("screenChange",(0,g.z)(this.BT,this)));this.o.push(this.dd.$_s("onlineScreenChange",(0,g.z)(this.PP,this)))},z8=function(a){g.mH("cloudview",a)},Bwa=function(a){z8("setApiReady_ "+a);
g.ra("yt.mdx.remote.cloudview.apiReady_",a,void 0)},A8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Cwa=function(a){g.pG[a]&&(a=g.pG[a],(0,g.H)(a,function(a){g.nG[a]&&delete g.nG[a]}),a.length=0)},Dwa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},B8=function(){return g.x("yt.mdx.remote.connection_")},C8=function(a){g.ra("yt.mdx.remote.connectData_",a,void 0)},Ewa=function(a){g.ra("yt.mdx.remote.currentScreenId_",a,void 0)},D8=function(){return g.x("yt.mdx.remote.currentScreenId_")},
F8=function(){if(!E8){var a=g.x("yt.mdx.remote.screenService_");
E8=a?new y8(a):null}return E8},G8=function(a){g.ra("yt.mdx.remote.cloudview.initializing_",a,void 0)},H8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},I8=function(a){z8("setCastInstalled_ "+a);
g.ZG("yt-remote-cast-installed",a)},J8=function(a){g.mH("cloudview",a)},Fwa=function(a,b){A8().init(a,b)},K8=function(){return!!g.$G("yt-remote-cast-installed")},Gwa=function(){z8("dispose");
var a=A8();a&&a.dispose();g.ra("yt.mdx.remote.cloudview.instance_",null,void 0);Bwa(!1);g.rG(L8);L8.length=0},Hwa=function(){var a=window.document.createElement("a");
g.Jd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ta(a)},Iwa=function(a,b){var c=g.ne("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Kd(c,g.eh("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Jwa=function(a){var b=g.mG();
if(b)if(b.clear(a),a)Cwa(a);else for(var c in g.pG)Cwa(c)},M8=function(){var a=Dwa();
a&&a(!1,"No cast extension found")},N8=function(a){return 0<=window.navigator.userAgent.indexOf(a)},O8=function(a,b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},Kwa=function(a,b){var c=new window.XMLHttpRequest;
c.onreadystatechange=function(){4==c.readyState&&200==c.status&&b(!0)};
c.onerror=function(){b(!1)};
try{c.open("GET",a,!0),c.send()}catch(d){b(!1)}},P8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},R8=function(a){var b=B8();
C8(null);a||Ewa("");g.ra("yt.mdx.remote.connection_",a,void 0);Q8&&((0,g.H)(Q8,function(b){b(a)}),Q8.length=0);
b&&!a?g.uG("yt-remote-connection-change",!1):!b&&a&&g.uG("yt-remote-connection-change",!0)},Lwa=function(){return g.x("yt.mdx.remote.connectData_")},S8=function(){var a=D8();
if(!a)return null;var b=F8().ge();return g.yH(b,a)},Mwa=function(a,b){I8(!0);
G8(!1);Fwa(a,function(a){a?(Bwa(!0),g.sG("yt-remote-cast2-api-ready")):(J8("Failed to initialize cast API."),I8(!1),g.aH("yt-remote-cast-available"),g.aH("yt-remote-cast-receiver"),Gwa());b(a)})},Nwa=function(){return K8()?A8()?A8().getCastSession():(J8("getCastSelector: Cast is not initialized."),null):(J8("getCastSelector: Cast API is not installed!"),null)},Owa=function(){var a=Hwa(),b=window.document.getElementById(a),c=b&&g.CF(b,"loaded");
c||b&&!c||(b=Iwa(a,function(){g.CF(b,"loaded")||(g.DF(b,"loaded","true"),g.sG(a),g.IE(g.Aa(Jwa,a),0))}))},Pwa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},Qwa=function(){if(g.tpa){var a=2,b=Dwa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;O8("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",M8,c)}},T8=function(a){if(a>=g.vpa.length)M8();
else{var b=g.vpa[a],c="chrome-extension://"+b+g.spa;0<=g.K2.indexOf(b)?Kwa(c,function(d){d?(window.chrome.cast=window.chrome.cast||{},window.chrome.cast.extensionId=b,O8(c,M8)):T8(a+1)}):O8(c,function(){T8(a+1)})}},V8=function(a,b){D8();
S8()&&S8();Ewa(a.id);var c=new g.EI(U8,a,P8());c.connect(b,Lwa());c.subscribe("beforeDisconnect",function(a){g.uG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){B8()&&(B8(),R8(null))});
R8(c)},W8=function(){var a=g.GH();
if(!a)return null;var b=F8().ge();return g.yH(b,a)},X8=function(a){g.mH("remote",a)},Y8=function(){var a=B8();
return!!a&&3!=a.getProxyState()},Z8=function(){H8()?A8().stopSession():J8("stopSession called before API ready.");
var a=B8();a&&(a.disconnect(1),R8(null))},Rwa=function(){var a=F8().dd.$_gos();
var b=S8();b&&B8()&&(g.xH(a,b)||a.push(b));return Pwa(a)},a9=function(a,b){g.dG.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.MB;this.A=this.o=null;this.I=(0,g.z)(this.XN,this);this.F=(0,g.z)(this.kl,this);this.G=(0,g.z)(this.WN,this);this.J=(0,g.z)(this.kO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.gu,this),Swa(this))):c=3;0!=c&&(b?this.gu(c):g.IE((0,g.z)(function(){this.gu(c)},this),0));
var d=Nwa();d&&$8(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},b9=function(a){return new g.tI(a.B.getPlayerContextData())},Twa=function(a,b,c,d,e){var f=b9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.xI(f,b,d);g.t(c)&&(g.vI(f,c),l.currentTime=c);g.t(k)&&(l.listId=k);c9(a,"setPlaylist",l);e||d9(a,f)},Swa=function(a){(0,g.H)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.Aa(this.gQ,a),this))},a)},Uwa=function(a){(0,g.H)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},e9=function(a,b){50>a.C.Kc()&&g.OB(a.C,b)},f9=function(a,b,c){var d=b9(a);
g.vI(d,c);-1E3!=d.g&&(d.g=b);d9(a,d)},c9=function(a,b,c){a.B.sendMessage(b,c)},d9=function(a,b){Uwa(a);
a.B.setPlayerContextData(g.yI(b));Swa(a)},$8=function(a,b){a.A&&(a.A.removeUpdateListener(a.I),a.A.removeMediaListener(a.F),a.kl(null));
a.A=b;a.A&&(g9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.I),a.A.addMediaListener(a.F),a.A.media.length&&a.kl(a.A.media[0]))},Vwa=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=b9(a);b.contentId!=d.videoId&&g9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.vI(d,a.o.getEstimatedTime());d9(a,d)}else g9("No cast media video. Ignoring state update.")},g9=function(a){g.mH("CP",a)},h9=function(a,b,c){return(0,g.z)(function(a){this.hc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.hc("Retrying "+b+" using MDx browser channel."),c9(this,b,c))},a)},Wwa=function(a,b){var c=!1;
A8()||(c=new g.nI(a,b),c.subscribe("yt-remote-cast2-availability-change",function(a){g.ZG("yt-remote-cast-available",a);g.uG("yt-remote-cast2-availability-change",a)}),c.subscribe("yt-remote-cast2-receiver-selected",function(a){z8("onReceiverSelected: "+a.friendlyName);
g.ZG("yt-remote-cast-receiver",a);g.uG("yt-remote-cast2-receiver-selected",a)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(a){z8("onReceiverResumed: "+a.friendlyName);
g.ZG("yt-remote-cast-receiver",a)}),c.subscribe("yt-remote-cast2-session-change",function(a){z8("onSessionChange: "+g.uH(a));
a||g.aH("yt-remote-cast-receiver");g.uG("yt-remote-cast2-session-change",a)}),g.ra("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
z8("cloudview.createSingleton_: "+c);return c},Xwa=function(){var a=0<=g.Ib.search(/\ (CrMo|Chrome|CriOS)\//);
return g.bF||a},i9=function(a,b){H8()?A8().setConnectedScreenStatus(a,b):J8("setConnectedScreenStatus called before ready.")},Ywa=function(){z8("clearCurrentReceiver");
g.aH("yt-remote-cast-receiver")},Zwa=function(){if(N8("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){Qwa();a({command:"cast.sender.init"});return}}if(!window.chrome||N8("Edge"))M8();else if(Qwa(),N8("Android")&&N8("Chrome/")&&window.navigator.presentation){var a="",b=g.Gh();55<=b?a="55":50<=b&&(a="50");O8("//www.gstatic.com/eureka/clank"+a+g.spa,M8)}else T8(0)},$wa=function(a){a?(g.ZG("yt-remote-session-app",a.app),g.ZG("yt-remote-session-name",a.name)):(g.aH("yt-remote-session-app"),g.aH("yt-remote-session-name"));
g.ra("yt.mdx.remote.channelParams_",a,void 0)},axa=function(){var a=P8();
if(g.Vb(a)){var a=g.FH(),b=g.$G("yt-remote-session-name")||"",c=g.$G("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.ra("yt.mdx.remote.channelParams_",a,void 0)}},bxa=function(){var a=W8();
a?(X8("Resume connection to: "+g.uH(a)),V8(a,0)):(g.NH(),Ywa(),X8("Skipping connecting because no session screen found."))},cxa=function(a){X8("remote.onCastSessionChange_: "+g.uH(a));
if(a){var b=S8();b&&b.id==a.id?i9(b.id,"YouTube TV"):(b&&Z8(),V8(a,1))}else B8()&&Z8()},dxa=function(){var a=Rwa(),b=S8();
b||(b=W8());return g.ab(a,function(a){return b&&g.rH(b,a.key)?!0:!1})},exa=function(){var a=g.$G("yt-remote-cast-receiver");
return a?a.friendlyName:null},fxa=function(a,b,c,d,e){Xwa()?Wwa(b,e)&&(G8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?Mwa(a,c):(window.__onGCastApiAvailable=function(b,d){b?Mwa(a,c):(J8("Failed to load cast API: "+d),I8(!1),G8(!1),g.aH("yt-remote-cast-available"),g.aH("yt-remote-cast-receiver"),Gwa(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Owa():Zwa())):z8("Cannot initialize because not running Chrome")},
gxa=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.zg(a)||"";b&&(this.port=":"+b);this.domain=g.yg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Sa(a,"10.0")&&(this.o=!1))},hxa=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);
return c},j9=function(){var a=dxa();
!a&&K8()&&exa()&&(a={key:"cast-selector-receiver",name:exa()});return a},ixa=function(){var a=Rwa();
K8()&&g.$G("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},jxa=function(a){var b={device:"Desktop",
app:"youtube-desktop"},b=g.ZD("MDX_CONFIG")||b;g.XG&&Awa();g.HH();U8||(U8=new gxa(b?b.loungeApiHost:void 0),g.PH()&&(U8.g="/api/loungedev"));Q8||(Q8=g.x("yt.mdx.remote.deferredProxies_")||[],g.ra("yt.mdx.remote.deferredProxies_",Q8,void 0));axa();var c=F8();if(!c){var d=new g.$H(U8);g.ra("yt.mdx.remote.screenService_",d,void 0);c=F8();fxa(a,d,function(a){a?D8()&&i9(D8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.uG("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript),
b?b.appId:void 0)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.ra("yt.mdx.remote.initialized_",!0,void 0),X8("Initializing: "+g.qg(b)),k9.push(g.qG("yt-remote-cast2-availability-change",function(){g.uG("yt-remote-receiver-availability-change")})),k9.push(g.qG("yt-remote-cast2-receiver-selected",function(){C8(null);
g.uG("yt-remote-auto-connect","cast-selector-receiver")})),k9.push(g.qG("yt-remote-cast2-receiver-resumed",function(){g.uG("yt-remote-receiver-resumed","cast-selector-receiver")})),k9.push(g.qG("yt-remote-cast2-session-change",cxa)),k9.push(g.qG("yt-remote-connection-change",function(a){a?i9(D8(),"YouTube TV"):W8()||(i9(null,null),Ywa())})),a=P8(),b.isAuto&&(a.id+="#dial"),g.kF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),X8(" -- with channel params: "+
g.qg(a)),$wa(a),c.start(),D8()||bxa())},l9=function(){K8()?A8()?H8()?(z8("Requesting cast selector."),A8().requestSession()):(z8("Wait for cast API to be ready to request the session."),L8.push(g.qG("yt-remote-cast2-api-ready",l9))):J8("requestCastSelector: Cast is not initialized."):J8("requestCastSelector: Cast API is not installed!")},m9=function(a,b,c){g.L.call(this);
this.F=a;this.T=b;this.o=new g.aG(this);g.M(this,this.o);this.o.R(b,"onCaptionsTrackListChanged",this.jP);this.o.R(b,"captionschanged",this.VN);this.o.R(b,"captionssettingschanged",this.hC);this.o.R(b,"videoplayerreset",this.ko);this.o.R(b,"mdxautoplaycancel",this.MG);this.N=this.o.R(b,"onVolumeChange",this.CA);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.NA,this);c.subscribe("remotePlayerChange",this.ol,this);c.subscribe("remoteQueueChange",this.ko,this);c.subscribe("autoplayUpNext",this.pA,
this);c.subscribe("previousNextChange",this.KA,this);c.subscribe("nowAutoplaying",this.DA,this);c.subscribe("autoplayDismissed",this.oA,this);this.suggestion=null;this.G=new g.mQ(64);this.A=new g.Ct(this.cC,500,this);g.M(this,this.A);this.B=new g.Ct(this.dC,1E3,this);g.M(this,this.B);this.C={};this.J=new g.Ct(this.uC,1E3,this);g.M(this,this.J);this.I=new g.ik(this.TL,1E3,this);g.M(this,this.I);this.L=g.y;this.hC();this.ko();this.ol()},n9=function(a,b){var c=a.F,d=a.T.ga().lengthSeconds;
c.I=b||0;c.g.X("progresssync",b,d)},kxa=function(a){n9(a,0);
a.A.stop();o9(a,new g.mQ(64))},q9=function(a,b){if(p9(a)&&!a.D){var c=null;
b&&(c={style:a.T.si()},g.ac(c,b));a.g.VB(a.T.ga().videoId,c);a.C=b9(a.g).o}},r9=function(a,b){var c=a.T.Sf();
c?Twa(a.g,a.T.ga().videoId,b,c.de(),c.listId.toString()):Twa(a.g,a.T.ga().videoId,b);o9(a,new g.mQ(1))},lxa=function(a,b){if(b){var c=a.T.xc("captions","tracklist",{by:1});
c&&c.length?(a.T.Dd("captions","track",b),a.D=!1):(a.T.Tk("captions"),a.D=!0)}else a.T.Dd("captions","track",{})},p9=function(a){return b9(a.g).videoId==a.T.ga().videoId},o9=function(a,b){a.B.stop();
var c=a.G;if(!g.sQ(c,b)){var d=g.W(b,2);if(d!=g.W(a.G,2)){var e=a.T;g.h2(e.app,d,e.playerType)}a.G=b;mxa(a.F,c,b)}},s9=function(a){g.Y.call(this,{H:"div",
M:"ytp-remote",K:[{H:"div",M:"ytp-remote-display-status",K:[{H:"div",M:"ytp-remote-display-status-icon",K:[g.dE()]},{H:"div",M:"ytp-remote-display-status-text",K:["{{statustext}}"]}]}]});this.o=new g.fW(this,250);g.M(this,this.o);this.A=a;this.R(a,"presentingplayerstatechange",this.B);nxa(this,g.dV(a))},nxa=function(a,b){if(3==a.A.Ya()){var c={RECEIVER_NAME:a.A.xc("remote","currentReceiver").name},c=g.W(b,128)?g.U("YTP_MDX_STATUS_ERROR_2",c):b.xb()||g.W(b,4)?g.U("YTP_MDX_STATUS_PLAYING_2",c):g.U("YTP_MDX_STATUS_CONNECTED_2",
c);
a.Ga("statustext",c);a.o.show()}else a.o.hide()},t9=function(a){g.WV.call(this,a);
this.A={key:g.wH(),name:g.U("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.mQ(64);this.I=0;var b=g.XU(a).F;b&&(b=b.A&&b.A.g)&&(b=new x8(a,b),g.M(this,b));b=new s9(a);g.M(this,b);g.yV(a,b.element,4)},mxa=function(a,b,c){a.F=c;
a.g.X("presentingplayerstatechange",new g.xQ(c,b))},u9=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)Z8();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.ga().videoId;if(c||d){var e=a.g.Sf();if(e){var f=[];for(var k=0;k<e.getLength();k++)f[k]=e.dc(k).videoId}else f=[a.g.ga().videoId];c={videoIds:f,listId:c,videoId:d,index:Math.max(a.g.Py(),0),currentTime:a.g.getCurrentTime()}}else c=null;X8("Connecting to: "+g.qg(b));"cast-selector-receiver"==b.key?(C8(c||null),c=c||null,H8()?A8().setLaunchParams(c):J8("setLaunchParams called before ready.")):!c&&Y8()&&D8()==b.key?g.uG("yt-remote-connection-change",!0):
(Z8(),C8(c||null),c=F8().ge(),(c=g.yH(c,b.key))&&V8(c,1))}};
g.p(x8,g.k1);x8.prototype.I=function(){var a=this.T.xc("remote","receivers");a&&1<a.length&&!this.T.xc("remote","quickCast")?(this.F=g.Eb(a,this.B,this),g.l1(this,(0,g.I)(a,this.B)),a=this.T.xc("remote","currentReceiver"),this.pf(this.B(a)),this.enable(!0)):this.enable(!1)};
x8.prototype.B=function(a){return a.key};
x8.prototype.nf=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
x8.prototype.qd=function(a){g.k1.prototype.qd.call(this,a);this.T.Dd("remote","currentReceiver",this.F[a]);this.A.Ub()};
g.C(y8,g.zH);g.h=y8.prototype;g.h.ge=function(a){return this.dd.$_gs(a)};
g.h.contains=function(a){return!!this.dd.$_c(a)};
g.h.get=function(a){return this.dd.$_g(a)};
g.h.start=function(){this.dd.$_st()};
g.h.gp=function(a,b,c){this.dd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.dd.$_r(a,b,c)};
g.h.No=function(a,b,c,d){this.dd.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.o.length;a<b;++a)this.dd.$_ubk(this.o[a]);this.o.length=0;this.dd=null;y8.Z.W.call(this)};
g.h.BT=function(){this.X("screenChange")};
g.h.PP=function(){this.X("onlineScreenChange")};
var E8=null,L8=[],Q8=null,U8=null;g.C(a9,g.dG);g.h=a9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,h9(this,"play")):c9(this,"play"),f9(this,1,g.wI(b9(this))),this.X("remotePlayerChange")):e9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,h9(this,"pause")):c9(this,"pause"),f9(this,2,g.wI(b9(this))),this.X("remotePlayerChange")):e9(this,this.pause)};
g.h.HC=function(a){if(1==this.g){if(this.o){var b=b9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.xb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,h9(this,"seekTo",{newTime:a}))}else c9(this,"seekTo",{newTime:a});f9(this,3,a);this.X("remotePlayerChange")}else e9(this,g.Aa(this.HC,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,h9(this,"stopVideo")):c9(this,"stopVideo");var a=b9(this);a.index=-1;a.videoId="";g.uI(a);d9(this,a);this.X("remotePlayerChange")}else e9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=b9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){g9("set receiver volume: "+d)},this),(0,g.z)(function(){this.hc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){g9("set receiver muted: "+b)},this),(0,g.z)(function(){this.hc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);c9(this,"setVolume",e)}c.muted=b;c.volume=a;d9(this,c)}else e9(this,g.Aa(this.setVolume,a,b))};
g.h.VB=function(a,b){if(1==this.g){var c=b9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.qg(b.style),g.ac(d,c.o));c9(this,"setSubtitlesTrack",d);d9(this,c)}else e9(this,g.Aa(this.VB,a,b))};
g.h.fu=function(a,b){if(1==this.g){c9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Sc.id});var c=b9(this);c.audioTrackId=b.Sc.id;d9(this,c)}else e9(this,g.Aa(this.fu,a,b))};
g.h.GC=function(a,b){if(1==this.g){if(a&&b){var c=b9(this);g.xI(c,a,b);d9(this,c)}c9(this,"previous")}else e9(this,g.Aa(this.GC,a,b))};
g.h.FC=function(a,b){if(1==this.g){if(a&&b){var c=b9(this);g.xI(c,a,b);d9(this,c)}c9(this,"next")}else e9(this,g.Aa(this.FC,a,b))};
g.h.Aw=function(){1==this.g?c9(this,"dismissAutoplay"):e9(this,this.Aw)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.X("proxyStateChange",a,this.g)}a9.Z.dispose.call(this)};
g.h.W=function(){Uwa(this);this.B=null;this.C.clear();$8(this,null);a9.Z.W.call(this)};
g.h.gu=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.X("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.PB(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.gQ=function(a,b){this.X(a,b)};
g.h.XN=function(a){if(!a)this.kl(null),$8(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=b9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)g9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d9(this,b)}};
g.h.kl=function(a){g9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),Vwa(this),this.X("remotePlayerChange")};
g.h.WN=function(a){a?(Vwa(this),this.X("remotePlayerChange")):this.kl(null)};
g.h.kO=function(){var a=Nwa();a&&$8(this,a)};
g.h.hc=function(a){g.mH("CP",a)};
var k9=[];g.h=gxa.prototype;g.h.ci=function(a){var b=this.g;if(g.t(void 0)?0:this.o)b="https://"+this.domain+this.port+this.g;return g.Gg(b+a,{})};
g.h.eu=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Vb:g.Aa(this.wT,c,!0),onError:g.Aa(this.vT,d),Fd:g.Aa(this.xT,d)};b&&(c.Ob=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.WE(a,c)};
g.h.wT=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.vT=function(a,b){a(Error("Request error: "+b.status))};
g.h.xT=function(a){a(Error("request timed out"))};g.p(m9,g.L);g.h=m9.prototype;g.h.W=function(){g.L.prototype.W.call(this);this.A.stop();this.B.stop();this.L();this.g.unsubscribe("proxyStateChange",this.NA,this);this.g.unsubscribe("remotePlayerChange",this.ol,this);this.g.unsubscribe("remoteQueueChange",this.ko,this);this.g.unsubscribe("autoplayUpNext",this.pA,this);this.g.unsubscribe("previousNextChange",this.KA,this);this.g.unsubscribe("nowAutoplaying",this.DA,this);this.g.unsubscribe("autoplayDismissed",this.oA,this);this.g=this.F=null};
g.h.nz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(p9(this)){if(1081!=b9(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":b9(this.g).xb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.ej(c[0],c[1]);break;case "control_subtitles_set_track":q9(this,c[0]);break;case "control_set_audio_track":c=c[0],p9(this)&&this.g.fu(this.T.ga().videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":r9(this,this.T.getCurrentTime());break;case "control_seek":r9(this,c[0]);break;case "control_subtitles_set_track":q9(this,c[0]);break;case "control_set_audio_track":c=c[0],p9(this)&&this.g.fu(this.T.ga().videoId,c)}};
g.h.VN=function(a){this.nz("control_subtitles_set_track",g.Vb(a)?null:a)};
g.h.hC=function(){var a=this.T.xc("captions","track");g.Vb(a)||q9(this,a)};
g.h.CA=function(a){if(p9(this)){this.g.unsubscribe("remotePlayerChange",this.ol,this);var b=Math.round(a.volume);a=!!a.muted;var c=b9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.J.start();this.g.subscribe("remotePlayerChange",this.ol,this)}};
g.h.jP=function(){g.Vb(this.C)||lxa(this,this.C);this.D=!1};
g.h.NA=function(a,b){this.B.stop();2==b&&this.dC()};
g.h.ol=function(){if(p9(this)){this.A.stop();var a=b9(this.g);switch(a.g){case 1081:o9(this,new g.mQ(8));break;case 1:this.cC();o9(this,new g.mQ(8));break;case 1083:case 3:o9(this,new g.mQ(9));break;case 0:o9(this,new g.mQ(2));this.I.stop();n9(this,this.T.ga().lengthSeconds);break;case 1082:o9(this,new g.mQ(4));break;case 2:o9(this,new g.mQ(4));n9(this,g.wI(a));break;case -1:o9(this,new g.mQ(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},o9(this,new g.mQ(128,
a))}var a=b9(this.g).o,b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,lxa(this,a));a=b9(this.g);-1==a.volume||Math.round(this.T.getVolume())==a.volume&&this.T.Ne()==a.muted||this.J.isActive()||this.uC()}else kxa(this)};
g.h.KA=function(){this.T.X("mdxpreviousnextchange")};
g.h.ko=function(){p9(this)||kxa(this)};
g.h.MG=function(){this.g.Aw()};
g.h.pA=function(a){a&&(a=g.WE("/watch_queue_ajax",{method:"GET",Yc:{action_get_watch_queue_item:1,video_id:a},Vb:(0,g.z)(this.gR,this)}))&&(this.L=(0,g.z)(a.abort,a))};
g.h.gR=function(a,b){var c=new g.BP({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.T.X("mdxautoplayupnext",c)};
g.h.DA=function(a){(0,window.isNaN)(a)||this.T.X("mdxnowautoplaying",a)};
g.h.oA=function(){this.T.X("mdxautoplaycanceled")};
g.h.TL=function(a,b){-1==b9(this.g).g?r9(this,a):b&&this.g.HC(a)};
g.h.uC=function(){if(p9(this)){var a=b9(this.g);this.o.Ca(this.N);a.muted?this.T.mute():this.T.Vf();this.T.setVolume(a.volume);this.N=this.o.R(this.T,"onVolumeChange",this.CA)}};
g.h.cC=function(){this.A.stop();if(!this.g.ma()){var a=b9(this.g);a.xb()&&o9(this,new g.mQ(8));n9(this,g.wI(a));this.A.start()}};
g.h.dC=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(s9,g.Y);s9.prototype.B=function(a){nxa(this,a.state)};g.p(t9,g.WV);g.h=t9.prototype;g.h.create=function(){jxa("embedded"==g.X(this.g).g);this.D.push(g.qG("yt-remote-before-disconnect",this.SN,this));this.D.push(g.qG("yt-remote-connection-change",this.qQ,this));this.D.push(g.qG("yt-remote-receiver-availability-change",this.LA,this));this.D.push(g.qG("yt-remote-auto-connect",this.oQ,this));this.D.push(g.qG("yt-remote-receiver-resumed",this.nQ,this));this.LA()};
g.h.load=function(){this.g.Xp();g.WV.prototype.load.call(this);this.C=new m9(this,this.g,this.o);var a=Lwa(),a=a?a.currentTime:0,b=Y8()?new a9(B8(),void 0):null;0==a&&b&&(a=g.wI(b9(b)));0!=a&&(this.I=a||0,this.g.X("progresssync",a,void 0));mxa(this,this.F,this.F);g.m2(this.g.app,6)};
g.h.unload=function(){this.g.X("mdxautoplaycanceled");this.B=this.A;g.Re(this.C,this.o);this.o=this.C=null;g.WV.prototype.unload.call(this);g.m2(this.g.app,5)};
g.h.W=function(){g.rG(this.D);g.WV.prototype.W.call(this)};
g.h.Yk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.nz.apply(this.C,[].concat([a],c instanceof Array?c:hxa(g.ma(c))))};
g.h.yH=function(){return this.loaded?this.C.suggestion:null};
g.h.Mf=function(){return this.o?b9(this.o).Mf:!1};
g.h.hasNext=function(){return this.o?b9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.yL=function(){var a=b9(this.o),b=this.g.ga();return{allowSeeking:this.g.Qd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+((0,g.G)()-a.A)/1E3:a.C,isPeggedToLive:1>=(a.F?a.B+((0,g.G)()-a.A)/1E3:a.B)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.F?a.B+((0,g.G)()-a.A)/1E3:a.B,seekableStart:0<a.D?a.D+((0,g.G)()-a.A)/1E3:a.D}};
g.h.zL=function(){this.o&&this.o.FC()};
g.h.AL=function(){this.o&&this.o.GC()};
g.h.SN=function(a){1==a&&(this.J=this.o?b9(this.o):null)};
g.h.qQ=function(){var a=Y8()?new a9(B8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Qe(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.ga().videoId&&this.g.Ny(a.videoId,g.wI(a)));this.g.X("videodatachange","newdata",this.g.ga(),3)};
g.h.LA=function(){this.G=[this.A].concat(ixa());var a=j9()||this.A;u9(this,a);this.g.xa("onMdxReceiversChange")};
g.h.oQ=function(){var a=j9();u9(this,a)};
g.h.nQ=function(){this.B=j9()};
g.h.xL=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?l9():u9(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&l9(),!0):!1}};
g.h.BL=function(){c9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Gd=function(){return!1};g.oZ.remote=t9;})(_yt_player);
